services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
    ports:
      - 5100:5000
    stdin_open: true
    tty: true

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/webapp
    ports:
      - 5173:5173
    stdin_open: true
    tty: true